version: '3.8'

services:
    mongo:
        image: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - mongo_data:/data/db
    redis:
        image: eqalpha/keydb
        restart: unless-stopped
    malwarecheckbot:
        image: ghcr.io/nycodeghg/malwarecheckbot
volumes:
    mongo_data:
