name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        env:
          DOCKER_USERNAME: nycodeghg
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - name: Build & Tag
        run: docker build -t ghcr.io/nycodeghg/malwarecheckbot:latest -t ghcr.io/nycodeghg/malwarecheckbot:"$GITHUB_SHA" .
      - name: Push Image to GitHub Container Registry
        run: docker push ghcr.io/nycodeghg/malwarecheckbot:latest
      - name: Push Specific Image to GitHub Container Registry
        run: docker push ghcr.io/nycodeghg/malwarecheckbot:"$GITHUB_SHA"
